project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!about_disabled.qmd"
  resources:
    - CNAME

website:
  title: ""
  site-url: "https://johanfourieza.github.io"
  favicon: images/icon.png
  google-analytics: "G-TQJEXD9NM3"
  open-graph:
    image: images/Johan_Fourie.jpg
    description: "Johan Fourie – Professor of Economics at Stellenbosch University"
  twitter-card:
    image: images/Johan_Fourie.jpg
    creator: "@johanfourieza"
    card-style: summary
  page-footer:
    center: "&copy; Johan Fourie"
  navbar:
    title: false
    alignment: center
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: students.qmd
        text: Students
      - href: teaching.qmd
        text: Teaching
      - href: public.qmd
        text: Public

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    back-to-top: true
    date-modified: last-modified

editor: visual
